#cloud-config

package_update: true
package_upgrade: true

packages:
    - python3-setuptools
    - python3-dev
    - build-essential
    - python3-pip
    - python-virtualenv
    - rabbitmq-server

runcmd:
    - [git, clone, https://github.com/xscanpix/acc-a3.git]
    - [cp, acc-a3/messaging, ~/]
    - [cd, ~/messaging]
    - [virtualenv, --no-site-packages, venv]
    - [source, venv/bin/activate]
    - [pip, install, celery]
    - [celery, worker, -A, tasks, &]