#cloud-config

package_update: true
package_upgrade: true

packages:
    - python-pip
    - rabbitmq-server
    - git

runcmd:
    - 'pip install python-keystoneclient'
    - 'pip install python-swiftclient'
    - 'pip install celery'
    - 'pip install flask'
    - 'cd /home/ubuntu'
    - 'git clone "https://github.com/xscanpix/acc-a3.git"'
    - 'cd /home/ubuntu/acc-a3/vm-creation'
    - 'export OS_AUTH_URL=https://uppmax.cloud.snic.se:5000/v3'
    - 'export OS_USERNAME="s11784"'
    - 'export OS_PASSWORD="apipassword1"'
    - 'unset OS_TENANT_ID'
    - 'unset OS_TENANT_NAME'
    - 'swift auth'
    - 'cd /home/ubuntu'
    - 'swift download svni7746-c3 data -p 0'
    - 'cd /home/ubuntu/acc-a3/messaging'
    - 'celery worker -A tasks.celery --loglevel=info &'
    - 'python tasks.py &'
