#cloud-config

package_update: true
package_upgrade: true

packages:
#    - python3-setuptools
#    - python3-dev
#    - build-essential
    - python3-pip
    - rabbitmq-server
    - git

runcmd:
    - [cd, ~]
    - [pip3, install, celery]
    - [git, clone, "https://github.com/xscanpix/acc-a3.git"]
    - [cd, ~/acc-a3/messaging]
    - [celery, worker, -A, tasks]
