#cloud-config

package_update: true
package_upgrade: true

packages:
    - python-pip
    - rabbitmq-server
    - git

runcmd:
    - 'cd /home/ubuntu/'
    - 'pip install celery'
    - 'pip install flask'
    - 'git clone "https://github.com/xscanpix/acc-a3.git"'
    - 'cd ./acc-a3/messaging'
    - 'celery worker -A tasks.celery --loglevel=info &'
    - 'python tasks.py &'
