heat_template_version: 2013-05-23

description: Hot Template to start a stack

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: "Ubuntu 16.04 LTS (Xenial Xerus) - latest"
  flavor: 
    type: string
    label: Flavor
    description: The flavor to be used
    default: "ACCHT18.normal"
  key:
    type: string
    label: Key name
    description: Name of key-pair
    default: 2svni7746
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to
    default: "SNIC 2018/10-30 Internal IPv4 Network"
  public_network:
    type: string
    label: Public network name or ID
    description: Public for floating ips
    default: "Public External IPv4 network"

resources:
  configuration:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash -v
        setenforce 0
        yum -y install docker-io
        cp /usr/lib/systemd/system/docker.service /etc/systemd/system/
        sed -i -e '/ExecStart/ { s,fd://,tcp://0.0.0.0:2375, }' /etc/systemd/system/docker.service
        systemctl start docker.service

  deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: { get_resource: configuration }
      server: { get_resource: svni-test-instance }

  svni-test-instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - network: { get_param: private_network }
      user_data_format: SOFTWARE_CONFIG

outputs:
  instance_ip:
    description: IP address of the instance
    value: { get_attr: [svni-test-instance, first_address] }
