version: '2'

services:
  rabbitmq:
    hostname: rabbit
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass

  flask:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - '5000:5000'

  celery:
    build: .
    command: celery worker -l info -A proj
    volumes:
      - .:/code
    depends_on:
      - rabbitmq