version: '2'

services:
  rabbitmq:
    hostname: rabbit
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
  flask:
    build: .
    command: python proj/tasks.py -m flask run --host=0.0.0.0
    ports:
      - '5000:5000'
    volumes: 
      - .:/code
  celery:
    build: .
    command: celery worker -l info -A tasks.celery
    volumes:
      - .:/code
    depends_on:
      - rabbitmq