version: '2'

services:
  rabbitmq:
    image: 'rabbitmq:3'
    ports:
      - '5672:5672'

  flask:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - '5000:5000'

  celery:
    build: .
    command: celery worker -l info -A tasks.celery