version: '2'

services:
  rabbitmq:
    image: 'rabbitmq: 3'
    hostname: rabbit1
    ports:
      - '5672:5672'
    environment: 
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    labels:
      NAME: rabbitmq1

  flask:
    build: .
    command: flask run --host=0.0.0.0 &
    volumes:
      - '.:.'
    ports:
      - '5000:5000'

  celery:
    build: .
    command: celery worker -l info -A tasks
    volumes:
      - '.:.'

volumes:
  rabbitmq: